[build]
  command = "npm run build"
  publish = "."
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"

[context.production]
  AKOOL_CLIENT_ID = "N/uZYSRNdjZwgps7i8iEzg=="
  AKOOL_CLIENT_SECRET = "bnFrXv1SqoX392wiM5vAdsOQVNjsHUbi"

[context.deploy-preview]
  AKOOL_CLIENT_ID = "N/uZYSRNdjZwgps7i8iEzg=="
  AKOOL_CLIENT_SECRET = "bnFrXv1SqoX392wiM5vAdsOQVNjsHUbi"

[context.branch-deploy]
  AKOOL_CLIENT_ID = "N/uZYSRNdjZwgps7i8iEzg=="
  AKOOL_CLIENT_SECRET = "bnFrXv1SqoX392wiM5vAdsOQVNjsHUbi"

[dev]
  port = 8888
  publish = "."
  functions = "netlify/functions"
  targetPort = 8888

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Development environment variables 
[context.dev.environment]
  NODE_ENV = "development"
  
# Production environment variables
[context.production.environment]
  NODE_ENV = "production"
